ims/apps/authentication/urls.py
from django.urls import path
from authentication.views import SignUpView, ProfileView, HomeView, EditUserProfileView, InvoiceView, InvoiceListView, InvoiceDetailView
from django.contrib.auth.views import LoginView, LogoutView

app_name='authentication'

urlpatterns = [
    path('accounts/signup/', SignUpView.as_view(), name='signup'),
    path('accounts/logout/', LogoutView.as_view(), name='logout'),
    path('accounts/profile/', EditUserProfileView.as_view(), name='profile'),
    path('create/invoice/', InvoiceView.as_view(), name='create_invoice'),
    path('invoice/list/', InvoiceListView.as_view(), name='invoice_list'),
    path('invoice/detail/<int:pk>/', InvoiceDetailView.as_view(), name='invoice_detail'),
    path('home/', HomeView.as_view(), name='home'),

    path('', LoginView.as_view(), name='login')
]

ims/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from .settings import base


urlpatterns = static(base.MEDIA_URL, document_root=base.MEDIA_ROOT)
urlpatterns += static(base.STATIC_URL, document_root=base.STATIC_ROOT)


urlpatterns += [
    path('admin/', admin.site.urls),

    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('authentication.urls')),

]

ims/apps/invoice/models.py
from django.db import models

# Create your models here.

ims/apps/authentication/forms.py
import django
from django import forms
from django.contrib.auth import (authenticate, get_user_model, password_validation)
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.utils.translation import ugettext_lazy as _

from authentication.models import CUser, Invoice, Item

UserModel = get_user_model()


class AuthenticationForm(forms.Form):
    """
    Base class for authenticating users. Extend this to get a form that accepts
    email/password logins.
    """
    email = forms.EmailField(
        label=_("Email address"),
        max_length=254,
        widget=forms.EmailInput(attrs={'autofocus': True}),
    )
    password = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput,
    )

    error_messages = {
        'invalid_login': _(
            "Please enter a correct %(username)s and password. Note that both "
            "fields may be case-sensitive."
        ),
        'inactive': _("This account is inactive."),
    }

    def __init__(self, request=None, *args, **kwargs):
        """
        The 'request' parameter is set for custom auth use by subclasses.
        The form data comes in via the standard 'data' kwarg.
        """
        self.request = request
        self.user_cache = None
        super().__init__(*args, **kwargs)

        self.username_field = UserModel._meta.get_field(UserModel.USERNAME_FIELD)

    def clean(self):
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')

        if email and password:
            self.user_cache = authenticate(self.request, email=email, password=password)
            if self.user_cache is None:
                if django.VERSION < (2, 1):
                    raise forms.ValidationError(
                        self.error_messages['invalid_login'],
                        code='invalid_login',
                        params={'username': self.username_field.verbose_name},
                    )

                raise self.get_invalid_login_error()
            else:
                self.confirm_login_allowed(self.user_cache)

        return self.cleaned_data

    def confirm_login_allowed(self, user):
        """
        Controls whether the given User may log in. This is a policy setting,
        independent of end-user authentication. This default behavior is to
        allow login by active users, and reject login by inactive users.

        If the given user cannot log in, this method should raise a
        ``forms.ValidationError``.

        If the given user may log in, this method should return None.
        """
        if not user.is_active:
            raise forms.ValidationError(
                self.error_messages['inactive'],
                code='inactive',
            )

    if django.VERSION < (2, 1):
        def get_user_id(self):
            if self.user_cache:
                return self.user_cache.id
            return None

    def get_user(self):
        return self.user_cache

    if django.VERSION >= (2, 1):
        def get_invalid_login_error(self):
            return forms.ValidationError(
                self.error_messages['invalid_login'],
                code='invalid_login',
                params={'username': self.username_field.verbose_name},
            )


class UserCreationForm(forms.ModelForm):
    """
    A form that creates a user, with no privileges, from the given email and
    password.
    """
    error_messages = {
        'password_mismatch': _("The two password fields didn't match."),
    }
    email = forms.EmailField(
        label=_("Email address"),
        max_length=254,
        widget=forms.EmailInput(attrs={'autofocus': True}),
    )
    password1 = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput,
        help_text=password_validation.password_validators_help_text_html(),
    )
    password2 = forms.CharField(
        label=_("Password confirmation"),
        widget=forms.PasswordInput,
        strip=False,
        help_text=_("Enter the same password as before, for verification."),
    )

    class Meta:
        model = CUser
        fields = ("email",)

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch',
            )
        return password2

    def _post_clean(self):
        super()._post_clean()
        # Validate the password after self.instance is updated with form data
        # by super().
        password = self.cleaned_data.get('password2')
        if password:
            try:
                password_validation.validate_password(password, self.instance)
            except forms.ValidationError as error:
                self.add_error('password2', error)

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    email = forms.EmailField(
        label=_("Email address"),
        max_length=254,
        widget=forms.EmailInput(),
    )
    password = ReadOnlyPasswordHashField(
        label=_("Password"),
        help_text=_(
            "Raw passwords are not stored, so there is no way to see this "
            "user's password, but you can change the password using "
            "<a href=\"{}\">this form</a>."
        ),
    )

    class Meta:
        model = CUser
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        if django.VERSION < (2, 1):
            self.fields['password'].help_text = self.fields['password'].help_text.format('../password/')
            f = self.fields.get('user_permissions')
            if f is not None:
                f.queryset = f.queryset.select_related('content_type')
        else:
            password = self.fields.get('password')
            if password:
                password.help_text = password.help_text.format('../password/')
            user_permissions = self.fields.get('user_permissions')
            if user_permissions:
                user_permissions.queryset = user_permissions.queryset.select_related('content_type')

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial.get('password')


class RegistrationForm(UserCreationForm):

    class Meta:
        model = UserModel
        fields = ['email', 'first_name', 'last_name', 'password1', 'password2', 'is_agent', 'is_manager']

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserModel

        fields = ['first_name' ,'last_name']

class InvoiceForm(forms.ModelForm):
    copy_of_invoice = forms.FileField(widget=forms.FileInput(attrs={'accept':'application/pdf'}))

    class Meta:
        model = Invoice

        fields = ['copy_of_invoice' ,'invoice_number', 'vendor_name' ,'list_of_item', 'invoice_date']

    def clean_copy_of_invoice(self):
        copy_of_invoice = self.cleaned_data.get('copy_of_invoice')
        if copy_of_invoice.size <= 2000000:
            return copy_of_invoice
        raise forms.ValidationError('accept only upto 2 mb file')

ims/apps/authentication/views.py
from django.shortcuts import render, redirect, HttpResponse, HttpResponseRedirect, get_object_or_404
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache
from django.views.generic import ListView, UpdateView, DetailView, CreateView, FormView, TemplateView, RedirectView
from django.contrib.auth.forms import AuthenticationForm
from django.views.generic.edit import FormView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from authentication.forms import RegistrationForm, UserProfileForm, InvoiceForm
from authentication.models import Invoice, Item
from django.urls import reverse, reverse_lazy

from django.contrib.auth import get_user_model

from authentication.utils import send_email

User = get_user_model()

class SignUpView(FormView):
    form_class = RegistrationForm
    template_name = 'registration/signup.html'

    def form_valid(self, form):
        user = form.save(False)
        user.set_password(form.cleaned_data.get('password1'))
        user.is_active = True
        user.save()

        user = authenticate(username=user.email, password=form.data['password1'])
        login(self.request, user)
        return HttpResponseRedirect(reverse('authentication:home'))

class ProfileView(LoginRequiredMixin, View):
    login_url = '/accounts/login/'

    def get(self, request):

        return render(request, 'registration/profile.html')


class EditUserProfileView(LoginRequiredMixin, UpdateView): #Note that we are using UpdateView and not FormView
    model = User
    form_class = UserProfileForm
    template_name = "registration/profile.html"

    def get_object(self, *args, **kwargs):

        user = get_object_or_404(User, pk=self.request.user.pk)

        # We can also get user object using self.request.user  but that doesnt work
        # for other models.

        return user

    def get_success_url(self, *args, **kwargs):
        return reverse("authentication:profile")


class HomeView(LoginRequiredMixin, TemplateView):
    template_name = 'deshboard.html'

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        if self.request.user.is_manager:
            data['invoices_count'] = Invoice.objects.all().count()
        else:   
            data['invoices_count'] = Invoice.objects.filter(user=self.request.user).count()
        return data


class InvoiceView(LoginRequiredMixin, CreateView):
    model = Invoice
    form_class = InvoiceForm
    template_name = 'authentication/invoice_create.html'

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            invoice = form.save(False)
            invoice.user = request.user
            invoice.save()

            #Send invoice detail with manager
            context = {}
            context['agent_email'] = invoice.user.email
            context['invoice_id'] = invoice.id
            context['invoice_number'] = invoice.invoice_number

            for manager in User.objects.filter(is_manager=True, is_active=True):
                context['manager_name'] = manager.get_full_name()
                send_email(context, 'email/invoice_detail_email.html', 'email/invoice_detail_email.txt', "New invoice Notification", manager.email)

            # return HttpResponseRedirect(reverse_lazy('authentication:invoice_detail', args=[invoce.id]))
            return HttpResponseRedirect(reverse_lazy('authentication:invoice_list'))

        return render(request, 'authentication/invoice_create.html', {'form': form})

class InvoiceListView(LoginRequiredMixin, ListView):
    queryset = Invoice.objects.all()
    model = Invoice
    template_name = 'authentication/invoice_list.html'

    def get_queryset(self):
        """
        Return the list of items for this view.
        The return value must be an iterable and may be an instance of
        `QuerySet` in which case `QuerySet` specific behavior will be enabled.
        """
        if self.request.user.is_manager:
            """If user is manager then return all invoices"""
            return self.queryset 
        else:
            """If user is agent then return only our invoices"""
            self.queryset = self.queryset.filter(user = self.request.user)
            return self.queryset


class InvoiceDetailView(LoginRequiredMixin, DetailView):
    model = Invoice
    form_class = InvoiceForm
    template_name = 'authentication/invoice_detail.html'

ims/apps/invoice/views.py
from django.shortcuts import render

# Create your views here.

ims/templates/base.html
{% load i18n static %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="icon" href="{% static 'img/favicon.ico' %}">

        <title>{% trans '(IMS)Invoice Management System' %}</title>

        <meta name="author" content="Vinod Kumar" />
        <meta name="description" content="" />
        <link rel='canonical' href=''/>

        {% block stylesheet %}
            <!-- Google font -->
            <link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,700" rel="stylesheet">

            <!-- Bootstrap -->
            <link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>

            <link type="text/css" rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}"/>

            <link type="text/css" rel="stylesheet" href="{% static 'css/custom.css' %}"/>
            
            <!-- For DataTable css-->
            <link href="{% static 'css/dataTables.min.css' %}" rel="stylesheet" media="screen">

        {% endblock %}

    </head>

    <body class="top-navigation">
        <div id="wrapper">
            <div id="page-wrapper" class="gray-bg">
                {% block header %}{% endblock %}
                {% block content %}{% endblock %}
                {% block footer %}{% endblock %}
            </div>
        </div>
    </body>
    
    {% block script %}
        <!-- jQuery Plugins -->
        <script src="{% static 'js/jquery.min.js' %}"></script>
        <script src="{% static 'js/jquery-3.5.1.slim.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/popper.min.js' %}"></script>

        <!-- For DataTable js-->
        <script src="{% static 'js/dataTables.min.js' %}" ></script>

        <!-- custom js-->

        {% block js%} {% endblock %}
    {% endblock %}
</html>

ims/templates/deshboard.html
{% extends 'layout.html' %}
{% load i18n static widget_tweaks%}

{% block title %}Home{% endblock %}

{% block content %}
    <div class="container-fluid">
        <button type="button" class="btn btn-dark"> <a href="{% url 'authentication:invoice_list' %}">Total Invoices {{invoices_count}}</span></a></button>
    </div>
{% endblock %}

ims/templates/footer.html
{% load i18n static %}

ims/templates/header.html
{% load i18n static %}
<header>
    {% if request.user.is_authenticated %}
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'authentication:home' %}">IMS</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'authentication:home' %}">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {{ request.user.get_full_name }}
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url 'authentication:profile' %}">Profile</a>
                            <a class="dropdown-item" href="{% url 'authentication:invoice_list' %}">Invoices</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'authentication:logout' %}">LogOut</a>
                        </div>
                    </li>
                </ul>
            </div>
        </nav>
    {% endif %}
</header>

ims/templates/layout.html
{% extends 'base.html' %}
{% load i18n static %}

{% block header %}
    {% include 'header.html' %}
{% endblock %}

{% block content %}

{% endblock %}

{% block footer %}
    {% include 'footer.html' %}
{% endblock %}